- hosts: all
  remote_user: ubuntu
  tasks:
  - name: Extracting file from jenkins workspace to target host.
    copy:
      src: "{{ BUILD_TAG }}"
      dest: /home/ubuntu/project/temp/
      
  - name: unzip the extracted file
    shell: unzip /home/ubuntu/project/temp/"{{ BUILD_TAG }}" -d /home/ubuntu/project/temp/project_files
    
  - name: Command to move extracted folder
    shell: mv -r /home/ubuntu/project/temp/project_files /home/ubuntu/project/project_files
  
  - name: Command to clear /home/ubuntu/project/temp folder
    shell: rm -rf /home/ubuntu/project/temp/*
    tags:
      - always
