- hosts: all
  remote_user: ubuntu
  tasks:
  - name: Extracting file from jenkins workspace to target host.
    copy:
      src: "{{ BUILD_TAG }}"
      dest: /home/ubuntu/project/temp/
  - name: unzip the extracted file
    shell: unzip "{{ BUILD_TAG }}"
